### ISSUE TITLE
There are too many TapToPlace scripts

### ISSUE THREAD

**Issue by timGerken** [Microsoft/MixedReality250#15]
Pick one:
MixedReality250\assets\HoloToolkit\Input\Scripts\Interactions\TapToPlace.cs
MixedReality250\assets\HoloToolkit\SpatialMapping\Scripts\TapToPlace.cs

**Comment by timGerken** [comment]
This is the correct version:
MixedReality250\assets\HoloToolkit\SpatialMapping\Scripts\TapToPlace.cs

**Comment by NeerajW** [comment]
Are you issuing the PR or should I?

**Comment by timGerken** [comment]
I will after my current PR is merged.
