### ISSUE TITLE
Unable to build project using Unity 2017.2.0b8

### ISSUE THREAD

**Issue by liuwuliuyun** [Microsoft/MixedReality250#5]
Symptom: when you finish adding all prefabs in Chapter 1 and start exporting Visual Studio solution, you'll get following error messages in Unity.

![capture](https://user-images.githubusercontent.com/17947406/29656958-b8d8698c-88e8-11e7-90d9-5af8988f9d96.PNG)

Testing Environment: Unity 2017.2.0b8

What I have tired:
1. Build an empty project and exporting Visual Studio solution on Unity 2017.2.0b8.
    Result: building succeed, working normal on HoloLens Emulator.
2. Export the whole project as a package and import the package into the empty project above.
    Result: still get above error messages.

Best Regards

Yun

**Comment by darax** [comment]
if you are enabling c# projects in the build settings, there is currently an issue with Unity which will lead to an error that looks like that.  Hopefully the next 2017.2 drop will have a fix.

**Comment by liuwuliuyun** [comment]
OK, I'll test it when the new stable version of Unity is avaliable. Thanks.
