### ISSUE TITLE
Current Unity Editor Project Version for master is still 2017.2b4 beta

### ISSUE THREAD

**Issue by GennadyK** [Microsoft/MixedReality250#6]
Hi guys,
In the readme it says: Current, Unity Editor Project Version: Unity 2017.2**b8** beta. But downloaded master has Unity 2017.2**b4** beta configured - b8 complains that the project is for b4.

I have installed VS 2017 v15. 3.3 and it's not working with Unity 2017.2b4:
https://forum.unity3d.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/

So to fix it I opened the latest master in Unity 2017.2b8 and was able to deploy the app. But something is broken as instead of the Unity splash object and the island object outside of initial window those two are running in the window and once window disappear you can only hear the sound and nothing is around.

![image](https://user-images.githubusercontent.com/14111397/30192077-117fe67a-9413-11e7-8711-777bdf7b31d1.png)

Thanks

**Comment by GennadyK** [comment]
This is what worked for me:
VS 2017 v15.3.3
Unity 2017.2b4 beta
Get MixedReality250 master from August the 2nd commit:
https://github.com/Microsoft/MixedReality250/tree/485857f5fdead6cdb0a2e535e6f24c65db746ad7

**DO NOT** check Unity C# Projects in the Unity Build Settings.

Once you got build error in VS, open this file:
...\MixedReality250\App\Mixed Reality Academy Project Island\project.lock.json
and change 4th line from:
    "UAP,Version=v10.0.10240": {
to:
    "UAP,Version=v10.0": {
Save it and do Debug->Start Without Debugging. Should be no error now and you will get the island the way it should be.

Thanks

**Comment by keveleigh** [comment]
Fixed via #13
